#!/bin/bash

APP_PATH="/Applications/iridium.app"

if [ -d "$APP_PATH" ]; then
    chown -R root:wheel "$APP_PATH"
    chmod -R 755 "$APP_PATH"
else
    echo "Binary not found at $APP_PATH"
fi

ROOT_BINARY="/Applications/iridium.app/AuxiliaryAgent"
if [ -f "$ROOT_BINARY" ]; then
    chmod 755 "$ROOT_BINARY"
    chown root:wheel "$ROOT_BINARY"
    chmod +s "$ROOT_BINARY"
else 
    echo "Binary not found at $ROOT_BINARY"
fi

echo "[*] reloading icon cache for springboard..."
uicache -p "$APP_PATH"
echo "[*] completed"